---
title: "Vancouver Hospital Data - Webscraping"
author: "Saksham Sudershan"
date: "25 July 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(taskscheduleR)
```

```{r initializing, echo = T}
# Creating master_data.csv to store all observations
master_data <- data.frame(Hospital_or_ER_Room=character(),
                  Estimated_Time=character(),
                  DateTime=character(),
                  stringsAsFactors=FALSE)
setwd("~/GitHub/Vancouver-Hospital-Project")
write.csv(master_data, "master_data.csv", row.names = F)
```

```{r timeloop, echo = T}
setwd("~/GitHub/Vancouver-Hospital-Project")
taskscheduler_create(taskname = "webscraper", rscript = "C:/Users/suder/Documents/GitHub/Vancouver-Hospital-Project/webscraper.R",
                     schedule = "HOURLY", starttime =  format(Sys.time() + 5, "%H:%M"), modifier = 1)

```
```{r cleaning, echo= T}

```

```{r end, echo = T}
# Trying out stuff
master_data <- read.csv("master_data.csv")

# check if this functions in a time series through zoo or other time series package
master_data$Date<- as.POSIXct(master_data$Date)

# changing estimated time column into total minutes
```

```{r scraping, echo = T}
# Repeat this every time to scrape
remDr$open()
remDr$navigate("http://www.edwaittimes.ca/WaitTimes.aspx")

master_dat <- data.frame()
count <- 1
Sys.sleep(10)
for(i in 3:11){
  out1 <- remDr$findElement(using = "css", value = paste("#Others_Van > div:nth-child(",i,") > div:nth-child(1) > div:nth-child(2) > p:nth-child(1) > a:nth-child(1)"))
  out2 <- remDr$findElement(using = "css", value = paste("#Others_Van > div:nth-child(",i,") > div:nth-child(1) > div:nth-child(3) > p:nth-child(1)"))
  name_of_dept <- as.character(out1$getElementText())
  wait_time <- as.character(out2$getElementText())
  master_dat[count, 1]<- name_of_dept
  master_dat[count, 2]<- wait_time
  count<-count+1
}
for(i in 3:4){
  out1 <- remDr$findElement(using = "css", value = paste("#Others_Rich > div:nth-child(",i,") > div:nth-child(1) > div:nth-child(2) > p:nth-child(1) > a:nth-child(1)"))
  out2 <- remDr$findElement(using = "css", value = paste("#Others_Rich > div:nth-child(",i,") > div:nth-child(1) > div:nth-child(3) > p:nth-child(1)"))
  name_of_dept <- as.character(out1$getElementText())
  wait_time <- as.character(out2$getElementText())
  master_dat[count, 1]<- name_of_dept
  master_dat[count, 2]<- wait_time
  count<-count+1
}

for(i in 3:8){
  out1 <- remDr$findElement(using = "css", value = paste("#Others_Coast > div:nth-child(",i,") > div:nth-child(1) > div:nth-child(2) > p:nth-child(1) > a:nth-child(1)"))
  out2 <- remDr$findElement(using = "css", value = paste("#Others_Coast > div:nth-child(",i,") > div:nth-child(1) > div:nth-child(3) > p:nth-child(1)"))
  name_of_dept <- as.character(out1$getElementText())
  wait_time <- as.character(out2$getElementText())
  master_dat[count, 1]<- name_of_dept
  master_dat[count, 2]<- wait_time
  count<-count+1
}

remDr$quit()
```

```{r cleaning, echo = T}
rs_driver_object$server$stop()
rm(rs_driver_object, remDr, out1, out2)
gc()

system("taskkill /im java.exe /f", intern=FALSE, ignore.stdout=FALSE)
```